### PR TITLE
(vec (map ...)) => (mapv ...)

### PR DESCRIPTION
**Pull request by pbudzik**
(into [](map ....) or (vec (map ...) => (mapv ...)

### CODE REVIEW

**Comment by danielcompton** [comment]
Hi @pbudzik, thanks for this. I'll look at it more closely when I'm back from break. In the meantime, can you add some tests for this suggestion? Thanks!

**Comment by pbudzik** [comment]
Done.

**Comment by danielcompton** [comment]
I'm a little conflicted on this, #83 already has raised that `into []` isn't always equivalent to `vec`, specifically in the case where you're using reducers. If you wanted to split this PR out into two parts then I'd be happy to merge the `(vec (map` part, and leave the `into []` part until we have a way to add metadata on rules to warn people about this.

#107

**Comment by NoahTheDuke** [comment]
Closing this PR in light of kibit entering maintenance status. (See [this comment](https://github.com/clj-commons/kibit/issues/250#issuecomment-2115570734) for further details.)

**Pull request closed without merging**
