### PR TITLE
Suggest when-not for if-not with single branch

### PR DESCRIPTION
**Pull request by bbakersmith**

### CODE REVIEW

**Comment by danielcompton** [comment]
Hey, is this still ok to merge? What was the reason for closing?

**Comment by bbakersmith** [comment]
I personally find this more clear, but I wasn't sure if there was consensus around this convention. Added a commit for the positive check as well and reopened. It's good to merge if you agree with the recommendation.

**Comment by danielcompton** [comment]
Similarly to #2, there isn't complete consensus around this. Being able to specify which rules are included will be helpful. I'll have a think about whether to merge this now, or once that is in. Thanks!

**Comment by NoahTheDuke** [comment]
Closing this PR in light of kibit entering maintenance status. (See [this comment](https://github.com/clj-commons/kibit/issues/250#issuecomment-2115570734) for further details.)

**Pull request closed without merging**
